DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS fridges CASCADE;
DROP TABLE IF EXISTS grocery_lists CASCADE;
DROP TABLE IF EXISTS fridge_items CASCADE;
DROP TABLE IF EXISTS grocery_items CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE fridges (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE grocery_lists (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE fridge_items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  fridge_id INTEGER REFERENCES fridges(id) ON DELETE CASCADE,
  date_stored DATE NOT NULL DEFAULT CURRENT_DATE,
  time_stored TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiry DATE,
  category VARCHAR(255) NOT NULL,
  image_URL VARCHAR(255),
  notes TEXT,
  date_removed DATE DEFAULT NULL
);

CREATE TABLE grocery_items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  grocery_list_id INTEGER REFERENCES grocery_lists(id) ON DELETE CASCADE,
  obtained BOOLEAN NOT NULL DEFAULT FALSE
);
